# Generated by Django 3.0.5 on 2020-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200419_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.CharField(default='no', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
