# Generated by Django 3.0.5 on 2020-04-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_otherskills_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherSkills',
            new_name='OtherSkill',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
