# Generated by Django 3.0.5 on 2020-04-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200419_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
