# Generated by Django 3.0.5 on 2020-04-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200419_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='typeProject',
            field=models.CharField(choices=[('Machine Learning', 'MachineLearning'), ('Data analytics', 'Dataanalytics'), ('Deep Learning', 'DeepLearning')], max_length=200),
        ),
    ]
