# Generated by Django 3.0.5 on 2020-04-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200419_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='typeProject',
            field=models.CharField(choices=[('MachineLearning', 'MachineLearning'), ('DataAnalytics', 'DataAnalytics'), ('DeepLearning', 'DeepLearning')], max_length=200),
        ),
    ]
