# Generated by Django 3.0.5 on 2020-04-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200420_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-dateStart']},
        ),
    ]
