# Generated by Django 3.0.5 on 2020-04-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200420_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-dateEnd']},
        ),
    ]
