# Generated by Django 3.0.5 on 2020-04-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200420_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-dateEnd']},
        ),
    ]
